before_install:
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
install:
  - sudo apt-get install texlive-full texlive
script:
  - pdflatex -synctex=1 -interaction=nonstopmode tfg.tex
  - bibtex tfg.aux
  - pdflatex -synctex=1 -interaction=nonstopmode tfg.tex 
  - pdflatex -synctex=1 -interaction=nonstopmode tfg.tex
